### ISSUE TITLE
Transliterate: give words that you don't know

### ISSUE THREAD

**Issue by lidavidm** [a7c/garden-of-words#53]
Might be frustrating, but gives you a sense that there's something out there that you might want to know

**Comment by lidavidm** [comment]
Need give up button for type in question

**Comment by lidavidm** [comment]
Like how Dark Room map stage makes you realize that you are unprepared very quickly

**Comment by a7c** [comment]
lol i actually thought of this too but i didn't have time to commit to implementing it :d

**Comment by lidavidm** [comment]
Prioritize next by know 2/3, know 1/3, etc (so you feel like you're close)

Maybe there could be a way to influence wander so it'll give you the necessary word next time you wander
